version: "3.10"
services:
  web:
    build: .
    command: bash -c "python -m scripts.train &&
         python -m scripts.eval --db WineQuality --table Metrics &&
         coverage run -m src.unit_tests.test_preprocess &&
         coverage run -m src.unit_tests.test_dao &&
         coverage combine &&
         coverage report -m"
    ports:
      - 8000:8000
    image: borisshapa/wine-quality:latest
    stdin_open: true
    tty: true
    depends_on:
      - mssql
    networks:
      - app-network
    environment:
      - USER_ID=SA
      - PASSWORD=Password123
      - SERVER=mssql,1433
  mssql:
    build:
      dockerfile: mssql.dockerfile
      context: .
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    volumes:
      - ./data/full.csv:/data/train_val.csv
    networks:
      - app-network

networks:
  app-network: