version: "3.10"
services:
  web:
    build: .
    command: bash -c "python -m scripts.train &&
         python -m scripts.eval --db WineQuality --table Metrics &&
         coverage run -m src.unit_tests.test_preprocess &&
         coverage run -a -m src.unit_tests.test_dao &&
         coverage report -m"
    ports:
      - 8000:8000
    image: borisshapa/wine-quality:latest
    depends_on:
      - mssql
    networks:
      - app-network
  mssql:
    build:
      dockerfile: mssql.dockerfile
      context: .
    ports:
      - "1433:1433"
    volumes:
      - ./data/train_val.csv:/data/train_val.csv
    networks:
      - app-network

networks:
  app-network: