version: "3.10"
services:
  web:
    build: .
#    command: bash -c "python -m scripts.split_train_val_test &&
#         python -m scripts.train &&
#         python -m scripts.eval &&
#         coverage run -m src.unit_tests.test_preprocess &&
#         coverage report -m"
    ports:
      - 8000:8000
    image: borisshapa/wine-quality:latest
    stdin_open: true
    tty: true
    depends_on:
      - mssql
    networks:
      - app-network
  mssql:
      image: "mcr.microsoft.com/mssql/server:2022-latest"
      ports:
          - "1433:1433"
      environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=Secret1234
      volumes:
          - "./drive:/var/opt/mssql"
      networks:
        - app-network

networks:
  app-network: