seed: 21
wandb: ~

data:
  db_name: "WineQuality"
  data_table: "Wines"
  metrics_table: "Metrics"
  val_ratio: 0.1
  test_ratio: 0.1
  cat_features_indices: [0]

model:
  iterations: 1000
  learning_rate: 0.1
  depth: 10
  l2_leaf_reg: 3
  task_type: "CPU"