pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials("borisshapa-dockerhub")
        DB_SERVER=credentials("db-server")
        MSSQL_CREDS=credentials("sa-mssql")
        LC_ALL = "en_US.UTF-8"
        LANG = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
    }

    stages {
        stage("Clone github repository") {
            steps {
                cleanWs()
                sh "git clone -b master https://github.com/borisshapa/wine-quality-db"
            }
        }
        stage("Login") {
            steps {
                sh "docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW"
            }
        }
        stage("Build and run docker container") {
            steps {
                dir("wine-quality-db") {
                    script{
                        try {
                            sh "docker compose build --build-arg USER_ID=$MSSQL_CREDS_USR --build-arg PASSWORD=$MSSQL_CREDS_PSW --build-arg SERVER=$DB_SERVER"
                        } finally {
                            sh "docker compose up -d"
                        }
                    }
                }
            }
        }
        stage("Checkout coverage report") {
            steps {
                dir("wine-quality-db") {
                    script {
                        try {
                            timeout(10) {
                                sh "docker compose up -d"
                                waitUntil {
                                    "exited" == sh(returnStdout: true,
                                    script: "docker inspect wine-quality-db-web-1 --format=\"{{ .State.Status }}\"").trim()
                                }
                            }
                        } finally {
                            sh "docker compose logs -t --tail 13 web"
                        }
                    }
                }
            }
        }
        stage("Push") {
            steps {
                sh "docker push borisshapa/wine-quality:latest"
            }
        }
    }
    post {
        always {
            sh "docker logout"
        }
    }
}